// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 AnmiTaliDev <anmitalidev@nuros.org>
#include "backend/nvm/asm_generator.hpp"

namespace agn::backend::nvm {

bool NVMAssemblyGenerator::hasReturnOrExit(const std::vector<ast::Statement>& stmts) {
    for (auto& stmt : stmts) {
        if (std::get_if<ast::ReturnStmt>(&stmt.node)) return true;
        if (auto* n = std::get_if<ast::InlineAsmStmt>(&stmt.node)) {
            for (auto& part : n->parts) {
                if (part.kind == ast::AsmPart::Kind::Literal && part.text.find("syscall") != std::string::npos &&
                    part.text.find("exit") != std::string::npos) {
                    return true;
                }
            }
        }
        if (auto* n = std::get_if<ast::IfStmt>(&stmt.node)) {
            if (hasReturnOrExit(n->thenBody)) return true;
            if (n->elseBody && hasReturnOrExit(*n->elseBody)) return true;
        }
        if (auto* n = std::get_if<ast::ForStmt>(&stmt.node)) {
            if (hasReturnOrExit(n->body)) return true;
        }
    }
    return false;
}

std::string NVMAssemblyGenerator::generateLabel(const std::string& prefix) {
    labelCounter_++;
    return prefix + "_" + currentFunction_ + "_" + std::to_string(labelCounter_);
}

void NVMAssemblyGenerator::emitVgaChar(uint8_t ch, uint8_t attr) {
    uint32_t val = (uint32_t(attr) << 8) | ch;
    output_ += "    push 0x" + std::to_string(vgaCursor_) + "\n";
    output_ += "    push 0x" + std::to_string(val) + "\n";
    output_ += "    store_abs\n";
    vgaCursor_ += 2;
}

void NVMAssemblyGenerator::emitVgaNewline() {
    vgaCursor_ = ((vgaCursor_ - 0xB8000) / 160 + 1) * 160 + 0xB8000;
    vgaCursor_ += 160;
    if (vgaCursor_ >= 0xB8F00) vgaCursor_ = 0xB8000 + (18 * 160);
}

std::string NVMAssemblyGenerator::generate(ast::Program& program) {
    output_ += ".NVM0\n; Generated by Agnostic Compiler\n\n";

    ast::Function* mainFn = nullptr;
    for (auto& f : program.functions) if (f.name == "main") mainFn = &f;
    if (mainFn) generateFunction(*mainFn, "main");

    for (auto& f : program.functions) {
        if (&f == mainFn) continue;
        std::string name = f.receiver ? (f.receiver->type + "_" + f.name) : f.name;
        generateFunction(f, name);
    }

    for (auto& [modName, mod] : program.modules) {
        if (modName == "stdio") continue;
        for (auto& f : mod.functions) {
            if (f.isExported) generateFunction(f, modName + "_" + f.name);
        }
    }

    return output_;
}

void NVMAssemblyGenerator::generateFunction(ast::Function& func, const std::string& fullName) {
    currentFunction_ = fullName;
    localVars_.clear();
    nextLocal_ = 0;

    output_ += "; Function: " + fullName + "\nfn_" + fullName + ":\n";

    if (func.receiver) {
        output_ += "    ; receiver: " + func.receiver->name + " -> local " + std::to_string(nextLocal_) + "\n";
        localVars_[func.receiver->name] = nextLocal_++;
    }
    for (auto& p : func.params) {
        output_ += "    ; param: " + p.name + " -> local " + std::to_string(nextLocal_) + "\n";
        localVars_[p.name] = nextLocal_++;
    }

    for (auto& stmt : func.body) generateStatement(stmt);

    if (func.name == "main" && !hasReturnOrExit(func.body)) {
        output_ += "    ; Main returns 0 by default\n    push 0\n    syscall exit\n";
    }
    output_ += "    ret\n\n";
}

void NVMAssemblyGenerator::generateStatement(ast::Statement& stmt) {
    if (auto* n = std::get_if<ast::VarDeclStmt>(&stmt.node)) {
        output_ += "    ; var " + n->name + "\n";
        if (n->value) generateExpression(*n->value);
        else output_ += "    push 0\n";
        uint8_t slot = nextLocal_++;
        localVars_[n->name] = slot;
        output_ += "    store " + std::to_string(slot) + "\n";
        return;
    }
    if (auto* n = std::get_if<ast::AssignmentStmt>(&stmt.node)) {
        generateExpression(n->value);
        auto it = localVars_.find(n->name);
        if (it != localVars_.end()) output_ += "    store " + std::to_string(it->second) + "\n";
        return;
    }
    if (auto* n = std::get_if<ast::IfStmt>(&stmt.node)) {
        generateExpression(n->condition);
        std::string elseLbl = generateLabel("else");
        std::string endLbl = generateLabel("endif");
        output_ += "    jz32 " + elseLbl + "\n";
        for (auto& s : n->thenBody) generateStatement(s);
        output_ += "    jmp32 " + endLbl + "\n" + elseLbl + ":\n";
        if (n->elseBody) for (auto& s : *n->elseBody) generateStatement(s);
        output_ += endLbl + ":\n";
        return;
    }
    if (auto* n = std::get_if<ast::ForStmt>(&stmt.node)) {
        std::string startLbl = generateLabel("for_start");
        std::string endLbl = generateLabel("for_end");
        output_ += startLbl + ":\n";
        if (n->condition) {
            generateExpression(*n->condition);
            output_ += "    jz32 " + endLbl + "\n";
        }
        for (auto& s : n->body) generateStatement(s);
        output_ += "    jmp32 " + startLbl + "\n" + endLbl + ":\n";
        return;
    }
    if (std::get_if<ast::ReturnStmt>(&stmt.node)) return;
    if (auto* n = std::get_if<ast::ExpressionStmt>(&stmt.node)) {
        generateExpression(n->expr);
        return;
    }
    if (auto* n = std::get_if<ast::PointerAssignmentStmt>(&stmt.node)) {
        generateExpression(n->target);
        generateExpression(n->value);
        output_ += "    store_abs\n";
        return;
    }
    if (auto* n = std::get_if<ast::ComptimeStmt>(&stmt.node)) {
        for (auto& s : n->body) generateStatement(s);
        return;
    }
}

void NVMAssemblyGenerator::generateExpression(ast::Expression& expr) {
    if (auto* n = std::get_if<ast::NumberExpr>(&expr.node)) {
        output_ += "    push " + std::to_string(n->value) + "\n";
        return;
    }
    if (std::get_if<ast::StringExpr>(&expr.node)) {
        output_ += "    push 0  ; string literals not supported in the VGA text listing\n";
        return;
    }
    if (auto* n = std::get_if<ast::IdentifierExpr>(&expr.node)) {
        auto it = localVars_.find(n->name);
        if (it != localVars_.end()) output_ += "    load " + std::to_string(it->second) + "\n";
        else output_ += "    push 0\n";
        return;
    }
    if (auto* n = std::get_if<ast::BinaryExpr>(&expr.node)) {
        generateExpression(*n->left);
        generateExpression(*n->right);
        switch (n->op) {
            case ast::BinaryOp::Add: output_ += "    add\n"; break;
            case ast::BinaryOp::Sub: output_ += "    sub\n"; break;
            case ast::BinaryOp::Mul: output_ += "    mul\n"; break;
            case ast::BinaryOp::Div: output_ += "    div\n"; break;
            case ast::BinaryOp::Mod: output_ += "    mod\n"; break;
            case ast::BinaryOp::Equal: output_ += "    eq\n"; break;
            case ast::BinaryOp::NotEqual: output_ += "    neq\n"; break;
            case ast::BinaryOp::Less: output_ += "    lt\n"; break;
            case ast::BinaryOp::Greater: output_ += "    gt\n"; break;
            case ast::BinaryOp::LessEqual: output_ += "    gt\n    push 0\n    eq\n"; break;
            case ast::BinaryOp::GreaterEqual: output_ += "    lt\n    push 0\n    eq\n"; break;
            case ast::BinaryOp::BitAnd: output_ += "    band\n"; break;
            case ast::BinaryOp::BitOr: output_ += "    bor\n"; break;
            case ast::BinaryOp::BitXor: output_ += "    bxor\n"; break;
            case ast::BinaryOp::Shl: output_ += "    shl\n"; break;
            case ast::BinaryOp::Shr: output_ += "    shr\n"; break;
            default: output_ += "    ; unsupported binary op\n"; break;
        }
        return;
    }
    if (auto* n = std::get_if<ast::UnaryExpr>(&expr.node)) {
        generateExpression(*n->operand);
        if (n->op == ast::UnaryOp::Neg) output_ += "    push 0\n    swap\n    sub\n";
        else output_ += "    push 0\n    eq\n";
        return;
    }
    if (auto* n = std::get_if<ast::CallExpr>(&expr.node)) {
        for (auto argIt = n->args.rbegin(); argIt != n->args.rend(); ++argIt) generateExpression(*argIt);
        output_ += "    call fn_" + n->function + "\n";
        return;
    }
    if (auto* n = std::get_if<ast::MethodCallExpr>(&expr.node)) {
        if (n->object == "stdio" && (n->member == "Print" || n->member == "Println") && !n->args.empty()) {
            if (auto* s = std::get_if<ast::StringExpr>(&n->args[0].node)) {
                for (unsigned char ch : s->value) emitVgaChar(ch, 0x07);
                if (n->member == "Println") emitVgaNewline();
                return;
            }
        }
        for (auto argIt = n->args.rbegin(); argIt != n->args.rend(); ++argIt) generateExpression(*argIt);
        output_ += "    call fn_" + n->object + "_" + n->member + "\n";
        return;
    }
    if (auto* n = std::get_if<ast::DerefExpr>(&expr.node)) {
        generateExpression(*n->operand);
        output_ += "    load_ptr\n";
        return;
    }
    output_ += "    push 0  ; unsupported expression in the VGA text listing\n";
}

} // namespace agn::backend::nvm
